//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BazaPoklonaWcfService.TrgovinaService1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Trgovina", Namespace="http://schemas.datacontract.org/2004/07/BazaPoklonaWcfService.Models")]
    [System.SerializableAttribute()]
    public partial class Trgovina : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTrgovinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivTrgovinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VrstaRobeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTrgovina {
            get {
                return this.IdTrgovinaField;
            }
            set {
                if ((this.IdTrgovinaField.Equals(value) != true)) {
                    this.IdTrgovinaField = value;
                    this.RaisePropertyChanged("IdTrgovina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NazivTrgovina {
            get {
                return this.NazivTrgovinaField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivTrgovinaField, value) != true)) {
                    this.NazivTrgovinaField = value;
                    this.RaisePropertyChanged("NazivTrgovina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VrstaRobe {
            get {
                return this.VrstaRobeField;
            }
            set {
                if ((this.VrstaRobeField.Equals(value) != true)) {
                    this.VrstaRobeField = value;
                    this.RaisePropertyChanged("VrstaRobe");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TrgovinaService1.ITrgovinaService")]
    public interface ITrgovinaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrgovinaService/DohvatiTrgovine", ReplyAction="http://tempuri.org/ITrgovinaService/DohvatiTrgovineResponse")]
        BazaPoklonaWcfService.TrgovinaService1.Trgovina[] DohvatiTrgovine();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrgovinaService/DohvatiTrgovine", ReplyAction="http://tempuri.org/ITrgovinaService/DohvatiTrgovineResponse")]
        System.Threading.Tasks.Task<BazaPoklonaWcfService.TrgovinaService1.Trgovina[]> DohvatiTrgovineAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrgovinaServiceChannel : BazaPoklonaWcfService.TrgovinaService1.ITrgovinaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrgovinaServiceClient : System.ServiceModel.ClientBase<BazaPoklonaWcfService.TrgovinaService1.ITrgovinaService>, BazaPoklonaWcfService.TrgovinaService1.ITrgovinaService {
        
        public TrgovinaServiceClient() {
        }
        
        public TrgovinaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TrgovinaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrgovinaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrgovinaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BazaPoklonaWcfService.TrgovinaService1.Trgovina[] DohvatiTrgovine() {
            return base.Channel.DohvatiTrgovine();
        }
        
        public System.Threading.Tasks.Task<BazaPoklonaWcfService.TrgovinaService1.Trgovina[]> DohvatiTrgovineAsync() {
            return base.Channel.DohvatiTrgovineAsync();
        }
    }
}
